sudo: required
services:
  - docker

before_install:
  - docker build -t multi-container-app/client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true multi-container-app/client npm run test

after_success:
  - docker build -t multi-container-app/client ./client
  - docker build -t multi-container-app/nginx ./nginx
  - docker build -t multi-container-app/server ./server
  - docker build -t multi-container-app/worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push multi-container-app/client
  - docker push multi-container-app/nginx
  - docker push multi-container-app/server
  - docker push multi-container-app/worker